### ISSUE TITLE
GPU settings

### ISSUE THREAD

**Issue by Alexey71** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#50] opened 2019-04-18 06:33 UTC
GPU Maximum/Minimum frequency and GPU Governor can not changed

https://drive.google.com/file/d/1IhlYBkAgvp806wTlT8ee3lM8mCvSsR12/view?usp=sharing

_Originally posted by @Alexey71 in https://github.com/franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest/issues/49#issuecomment-484374042_

**Comment by franciscofranco** [comment] 2019-04-21 19:08
The governor is not suposed to be changed to anything other than performance. The device needs the msm-adreno-tz to be running correctly. That's not my app's fault, it's a protection from the kernel.
About the max freq, it's working as intended. I don't know where Kernel Auditor is getting the freqs from, but I changed on my app and checked with the console and changed just fine after changing it to 400 MHz on my app:

mido:/ # cat /sys/class/devfreq/1c00000.qcom,kgsl-3d0/max_freq
400000000

There is no bug since my app is working as intended, so I'm closing this.

**Closed by franciscofranco** 2019-04-21 19:08 UTC

**Comment by Alexey71** [comment] 2019-04-21 20:37
/sys/devices/soc/1c00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk

**Comment by franciscofranco** [comment] 2019-04-22 03:55
That's not the correct path...

**Comment by franciscofranco** [comment] 2019-04-22 03:56
/sys/class/devfreq/1c00000.qcom,kgsl-3d0/max_freq
